include_recipe "chef-streambot-aws::access"
include_recipe "jenkins::server"
include_recipe "chef-streambot-jenkins::s3"
include_recipe "chef-streambot-jenkins::thin_backup"
include_recipe "chef-streambot-jenkins::backup_s3_upload"
include_recipe "chef-streambot-jenkins::build_ami"